spring:
  application:
    name: products
  cloud:
    config:
      profile: dev
      fail-fast: true
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
      retry:
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 60000
        max-attempts: 100

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10